### ISSUE TITLE
move AWS S3 to its own module

### ISSUE THREAD

**Issue by Dujota** [Tosin0814/Tinster#2]
https://github.com/Tosin0814/Tinster/blob/cafe1f4153a7d768eec0621adb477136cecc83a0/routes/posts.js#L9

notice that these are variables you are setting up here. 

normally you would create an S3 module in your /config folder (similar to the database or the passport files) it will have the functions that will return the value you expect back in the S3/uploader variables. 

you just import the functions and pass in the required data. this will allow you to share the s3 module accross your whole application

**Comment by Tosin0814** [comment]
I decided to create a single config file for multerS3 and AWS S3, called "multer_S3".
I chose this path because the multerS3 'upload' object requires data from to 's3' object and cannot function without it. I feel separate config files for both would be unnecessary in the context of Tinster.

**Comment by Dujota** [comment]
sure as long as you extract this into its own module , you should be good. 
it is important to note that there are many situations where you may be accessing different s3 buckets or different credentials, which is why i suggested same
